version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/home/app
    php:
        image: chartuniverse_php
        volumes:
            - ./app:/app            

            